name: test ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Hi
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v2
    - name: build
      run: |
        pwd
        go version
        echo $GOPATH
        echo $HOME
        echo $GITHUB_WORKSPACE
        find . -name "*"
