name: test ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Hi
    container:
      image: "golang:latest"
    steps:
    - name: build
      run: |
        go version
